### ISSUE TITLE
Implement @defended decorator.

### ISSUE THREAD

**Issue by proofit404** [proofit404/generics#50]
```python
from attr import attrs, attrib
from generics import defended
from stories import story

@defended
@attrs
class Purchase:

    @story
    def make(I):
        I.find_profile
        I.find_category
        I.find_movie

    # Steps.

    def find_profile(self, ctx):
        ctx.profile = self.load_profile(ctx.profile_id, is_active=True)
        return Success()

    def find_category(self, ctx):
        ctx.category = self.load_category(ctx.category_id)
        return Success()

    def find_movie(self, ctx):
        ctx.movie = self.load_movie(ctx.movie_id)
        return Success()

    # Dependencies.

    load_profile = attrib()
    load_category = attrib()
    load_book = attrib()
```
- [ ] Analyze source code of the methods to build a prototype of the encapsulated object
- [ ] Force user to use `@private` after `@defended` if user wants to use both
- [ ] set validator on `load_profile`
    - should have at least two arguments
    - one of the argument should have `is_active` name
    - `is_active` can't be the first one
- [ ] set validator on `load_category`
    - should have at least one argument
- [ ] support attrs
    - `load_category` and `load_profile` should not have validators or converters
- [ ] support dataclasses
- [ ] support pydantic
    - `load_category` and `load_profile` should be annotated as `Callable` without any type arguments

**Comment by proofit404** [comment]
Supersedes https://github.com/proofit404/dependencies/issues/248

**Comment by proofit404** [comment]
Converted to milestone https://github.com/proofit404/generics/milestone/2
